/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_camera_simplewebcam_CameraPreview */

#ifndef _Included_com_camera_simplewebcam_CameraPreview
#define _Included_com_camera_simplewebcam_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
#undef com_camera_simplewebcam_CameraPreview_DEBUG
#define com_camera_simplewebcam_CameraPreview_DEBUG 1L
#undef com_camera_simplewebcam_CameraPreview_IMG_WIDTH
#define com_camera_simplewebcam_CameraPreview_IMG_WIDTH 640L
#undef com_camera_simplewebcam_CameraPreview_IMG_HEIGHT
#define com_camera_simplewebcam_CameraPreview_IMG_HEIGHT 480L
/*
 * Class:     com_camera_simplewebcam_CameraPreview
 * Method:    prepareCamera
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_camera_simplewebcam_CameraPreview_prepareCamera
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_camera_simplewebcam_CameraPreview
 * Method:    prepareCameraWithBase
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_camera_simplewebcam_CameraPreview_prepareCameraWithBase
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_camera_simplewebcam_CameraPreview
 * Method:    processCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_camera_simplewebcam_CameraPreview_processCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_camera_simplewebcam_CameraPreview
 * Method:    stopCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_camera_simplewebcam_CameraPreview_stopCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_camera_simplewebcam_CameraPreview
 * Method:    pixeltobmp
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_camera_simplewebcam_CameraPreview_pixeltobmp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
